### ISSUE TITLE
python3 main.py SyntaxError

### ISSUE THREAD

**Issue by bxpana** [Inspirateur/DiscordWordCloud#4]
Get to the last step and try to run `python3 main.py` but end up getting the following error:
```
Traceback (most recent call last):
  File "/home/pi/Documents/DiscordWordCloud/main.py", line 8, in <module>
    import discord
  File "/home/pi/.local/lib/python3.9/site-packages/discord/__init__.py", line 20, in <module>
    from .client import Client, AppInfo, ChannelPermissions
  File "/home/pi/.local/lib/python3.9/site-packages/discord/client.py", line 38, in <module>
    from .state import ConnectionState
  File "/home/pi/.local/lib/python3.9/site-packages/discord/state.py", line 36, in <module>
    from . import utils, compat
  File "/home/pi/.local/lib/python3.9/site-packages/discord/compat.py", line 32
    create_task = asyncio.async
                          ^
SyntaxError: invalid syntax
```

**Comment by bxpana** [comment]
Ran `sudo python3 main.py` and got this:
```
Traceback (most recent call last):
  File "/home/pi/Documents/DiscordWordCloud/main.py", line 8, in <module>
    import discord
ModuleNotFoundError: No module named 'discord'
```

**Comment by Inspirateur** [comment]
The discord.py library was outdated, I switched to Pycord yesterday, maybe you can try installing the libs from requirements.txt again and see if it works ?

**Comment by bxpana** [comment]
I ended up finding a hosted bot instead. Thanks for the update though!
